<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Memesan_model extends CI_Model
{

    public $table = 'memesan';
    public $id = 'id_memesan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('*');
        $this->db->join('tiket', 'tiket.id_tiket = memesan.id_tiket','inner');
        $this->db->join('pemesan', 'pemesan.id_pemesan = memesan.id_pemesan','inner');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('*');
        $this->db->join('tiket', 'tiket.id_tiket = memesan.id_tiket','inner');
        $this->db->join('pemesan', 'pemesan.id_pemesan = memesan.id_pemesan','inner');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_memesan', $q);
	$this->db->or_like('id_pemesan', $q);
	$this->db->or_like('id_tiket', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select('*');
        $this->db->join('tiket', 'tiket.id_tiket = memesan.id_tiket','inner');
        $this->db->join('pemesan', 'pemesan.id_pemesan = memesan.id_pemesan','inner');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_memesan', $q);
	$this->db->or_like('pemesan.nama', $q);
	$this->db->or_like('tiket.id_tiket', $q);
	$this->db->or_like('jumlah', $q);
    $this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function verifikasi($id){
        $this->db->set('status', 'Verified');
         $this->db->where($this->id, $id);
          $query=$this->db->update('memesan');
            return $query;
    }

}

/* End of file Memesan_model.php */
/* Location: ./application/models/Memesan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-06-23 04:51:35 */
/* http://harviacode.com */